declare const styles: {
  readonly "card": string;
  readonly "chip": string;
  readonly "chipOn": string;
  readonly "chips": string;
  readonly "doneBtn": string;
  readonly "footer": string;
  readonly "grid": string;
  readonly "head": string;
  readonly "hint": string;
  readonly "lastActive": string;
  readonly "page": string;
  readonly "progress": string;
  readonly "progressBar": string;
  readonly "progressCount": string;
  readonly "progressDot": string;
  readonly "progressFill": string;
  readonly "progressLabel": string;
  readonly "progressRow": string;
  readonly "progressSubject": string;
  readonly "progressTotal": string;
  readonly "section": string;
  readonly "sectionWide": string;
  readonly "switchLink": string;
  readonly "syncing": string;
  readonly "who": string;
  readonly "whoBlock": string;
};
export = styles;

