declare const styles: {
  readonly "active": string;
  readonly "activeScene": string;
  readonly "btnLearnNav": string;
  readonly "btnLearnNavSm": string;
  readonly "cardLeaving": string;
  readonly "cardMeta": string;
  readonly "cardStage": string;
  readonly "cardWrapper": string;
  readonly "cards": string;
  readonly "counterStage": string;
  readonly "counterTop": string;
  readonly "deckShadow": string;
  readonly "emptyMsg": string;
  readonly "gridPage": string;
  readonly "gridSemDots": string;
  readonly "learnCardArea": string;
  readonly "learnCounter": string;
  readonly "learnDot": string;
  readonly "learnNav": string;
  readonly "learnProgressChecks": string;
  readonly "learnProgressDots": string;
  readonly "mobileNav": string;
  readonly "page": string;
  readonly "pageLearning": string;
  readonly "peekCard": string;
  readonly "peekScene": string;
  readonly "seen": string;
  readonly "throwLeft": string;
  readonly "throwRight": string;
};
export = styles;

